### ISSUE TITLE
[REQUEST] Add support for looping a sound clip

### ISSUE THREAD

**Issue by msdos** [dan0v/AmplitudeSoundboard#48]
![Screenshot 2022-08-08 at 02 09 09](https://user-images.githubusercontent.com/489034/183343807-2dfc3840-7548-486f-b986-4890af602c5f.png)

For example, add a "loop" option here to loop the sounds clip on queue.

**Comment by dan0v** [comment]
Hi, that's not a bad idea, but there are a few things to consider; Should a button to toggle this feature appear on playing clips in the queue? Only issue there is that if a clip is very short, you won't have a chance to enable looping before the queue clears. How can a clip be stopped once it's looping? If the loop option is at the queue level, you'd have to click the "X" or stop all audio to stop playback, If it would be enabled in the SoundClip edit window instead, you don't have the issue of short clips, but this type of clip would always have to be manually stopped, which probably means a hotkey to stop specific SoundClips will also need to be configurable, unless users just have to use the "stop all audio" hotkey instead. I guess hotkeys aren't relevant to you yet, since you're on macOS based on your other ticket, but it's still something to think about.

Do you have any suggestions as to which approach would be better for usability?

**Comment by msdos** [comment]
> If it would be enabled in the SoundClip edit window instead, you don't have the issue of short clips, but this type of clip would always have to be manually stopped

Indeed this is better from an usability perspective. I don't think too much thought will be needed for hotkeys and such: technically, it would become "a very long audio" that can always be stopped  like it's supposed to be stopped.

**Comment by dan0v** [comment]
Released in version 2.5.0
