### ISSUE TITLE
Update to MacOS  posted Jan 12 2024 loses previous version's settings.

### ISSUE THREAD

**Issue by teacup775** [dan0v/AmplitudeSoundboard#54]
**Describe the bug**
Update to MacOS  posted Jan 12 2024 loses previous version's settings.

**To Reproduce**
Updated app by copying it into Applications folder extracted tar file.

**Expected behavior**
Settings should be preserved

**Desktop (please complete the following information):**
 - OS:  Sonoma 14.2.1
 - Version 2.7.1

**Additional context**
I suppose I can just save and paste over any files, but I'd prefer to know where settings are stored.

**Comment by dan0v** [comment]
Hi, sorry to hear that. Amplitude stores its Mac configuration files at `/Users/{you}/.local/share/amplitude-soundboard` in a series of Json files. Could you please check if those files contain your expected settings? If yes, there's likely some Mac specific config read error going on. If not, they may have been overwritten for some reason which didn't show up during testing on Windows.

**Comment by teacup775** [comment]
When I restored to the previous version, specifically just the application, my settings were restored. Sniffing through the files, they were last touched *before* I applied the update, so the update doesn't find them.

So at least the app is non destructive, but I didn't try to touch any settings, which might cause it to.

I can later experiment with the new installation by caching the config files, doing some minimal configuration to put some files in place, then play around from there.

**Comment by dan0v** [comment]
Alright, two further investigation steps then;
(Please back up your configuration files, so that you can restore them and keep using the previous version of Amplitude until I can fix this)

1. Send me your Json files, so that I can see if maybe this is not a platform specific issue, but there's something specific to your configs which causes the configuration parsing to fail.
2. Clear the contents of the amplitude-soundboard configurations directory and see if using the latest version of Amplitude, the application correctly saves any sound clips / profiles / etc. which are created during normal use. Basically, if you can run the new version of Amplitude and it retains your settings after closing and reopening it, it could also be a useful hint.

**Comment by teacup775** [comment]
I have installed 2.7 and successfully saved a clip, quit and restarted the app and used the sound board. 

But all my old data is, as before, unmolested. This suggests it's finding a completely different location?

What's interesting is 2.7 remembers the last directory location from 2.6. No files in dot local share are being effected.

It's storing its data someplace else.


[amp.zip](https://github.com/dan0v/AmplitudeSoundboard/files/13929489/amp.zip)

**Comment by dan0v** [comment]
Lol. [Microsoft changed](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/8.0/getfolderpath-unix#macos) the LocalApplicationData folder location in Dotnet 8... 

Will think of some way to workaround.

**Comment by teacup775** [comment]
How thoughtful of them.


As a work around what's the new location?  I might as well test if anything else is amiss by patching the old files in

**Comment by dan0v** [comment]
`/Users/{you}/Library/Application Support/amplitude-soundboard`

**Comment by teacup775** [comment]
confirmed: pasting the files from .local into Application Support WORKS to restore setup with minimal testing.

Soundboard settings and outputs are all there.

**Comment by dan0v** [comment]
Thanks a lot. I'll get a fixed version out tonight. The version number should be visible in the bottom left corner of the About window.
![image](https://github.com/dan0v/AmplitudeSoundboard/assets/7658521/497bd97d-ee94-421c-ad9f-e88767415958)

**Comment by teacup775** [comment]
Oh right. About from the apple menu. %)

I've had a busy morning.

**Comment by dan0v** [comment]
This is fixed in 2.7.3 but you will need to delete the new directory which was created in `/Users/{you}/Library/Application Support/amplitude-soundboard` and then open 2.7.3 for your configurations to be moved to the new location automatically. If there is already a "new" config directory present, the migration will not occur.

**Comment by dan0v** [comment]
There's nothing else to be done then. Thanks for testing!

@all-contributors please add @teacup775 for User Testing
