### ISSUE TITLE
[QUESTION] Default volume vs output profiles

### ISSUE THREAD

**Issue by Newcool1230** [dan0v/AmplitudeSoundboard#87]
Hey there,

I've been looking around trying to find some answers regarding the different volume sliders but haven't found any concrete ones yet.

Currently on Version 2.10.2. There is a volume slider under the output profile and volume sliders inside the output profile settings.

I'm kinda confused in which controls what. Does the volume under "Output Profile" override the profile settings? or is it a maximum cap? If it does override it, if I have 2 different profile volumes (shown in the screenshot) do they both change to the outside number? or does it get added on? (30 + 15 and 15 + 15)

![amplitude_soundboard_cVjCt44ftt](https://github.com/user-attachments/assets/49d54c10-0057-42ed-a651-585c85fc150c)

Any additional info on the volume sliders would be very helpful thank you!

**Comment by dan0v** [comment]
Hi, here is how it is supposed to work;

1.  The profile level volume control is used to set generally how you want to balance the output of sounds between different devices. Maybe you want to blast your soundboard through your virtual microphone to your friends at full volume, but only hear the same sound in your own headphones at 1%.
2. The sound clip level volume control is used to normalize your different clips, so that if `YABADABADOO.mp3` is much louder than `whisper_asmr.wav`, you don't get deafened by one while not hearing the other.

With these two granularity levels, you should be able to get a comfortable output profile, as well as consistent volume from your different sound clips :)
